name: Format

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "tsconfig.json"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        name: Setup bun

      - name: Prettier
        run: bunx prettier --check "src/**/*.{ts,tsx}"
